/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package turistar.ui;

import turistar.model.Usuario;
import turistar.model.Local;

/**
 *
 * @author Serviços
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    //private SelecionarLugar selecionarLugarFrame;
    //private EditarUsuario editarUsuarioFrame;
    
    public Menu() {
        initComponents();
        //selecionarLugarFrame = new SelecionarLugar();
        //editarUsuarioFrame = new EditarUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Lugares = new javax.swing.JMenu();
        CadastrarLugares = new javax.swing.JMenuItem();
        ListarLugares = new javax.swing.JMenuItem();
        EditarLugares = new javax.swing.JMenuItem();
        RemoverLugares = new javax.swing.JMenuItem();
        MinhasInfos = new javax.swing.JMenu();
        VisualizarUsuarios = new javax.swing.JMenuItem();
        EditarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lugares.setText("Lugares");

        CadastrarLugares.setText("Cadastrar");
        CadastrarLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarLugaresActionPerformed(evt);
            }
        });
        Lugares.add(CadastrarLugares);

        ListarLugares.setText("Listar");
        ListarLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarLugaresActionPerformed(evt);
            }
        });
        Lugares.add(ListarLugares);

        EditarLugares.setText("Editar");
        Lugares.add(EditarLugares);

        RemoverLugares.setText("Remover");
        RemoverLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverLugaresActionPerformed(evt);
            }
        });
        Lugares.add(RemoverLugares);

        jMenuBar1.add(Lugares);

        MinhasInfos.setText("Minhas Informações");

        VisualizarUsuarios.setText("Visualizar");
        VisualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarUsuariosActionPerformed(evt);
            }
        });
        MinhasInfos.add(VisualizarUsuarios);

        EditarUsuario.setText("Editar");
        EditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuarioActionPerformed(evt);
            }
        });
        MinhasInfos.add(EditarUsuario);

        jMenuBar1.add(MinhasInfos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarLugaresActionPerformed
        //selecionarLugarFrame.setVisible(true);
        LugarPago lugarPagoFrame = new LugarPago();
        lugarPagoFrame.setVisible(true);
    }//GEN-LAST:event_CadastrarLugaresActionPerformed

    private void VisualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarUsuariosActionPerformed
        VisualizaUsuario visualizaUsuarioFrame = new VisualizaUsuario();
        visualizaUsuarioFrame.setVisible(true);
    }//GEN-LAST:event_VisualizarUsuariosActionPerformed

    private void EditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuarioActionPerformed
        //EditarUsuario editarUsuarioFrame = new EditarUsuario();
        //editarUsuarioFrame.setVisible(true);
    }//GEN-LAST:event_EditarUsuarioActionPerformed

    private void ListarLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarLugaresActionPerformed
        VisualizaLocal visualizaLocalFrame = new VisualizaLocal();
        visualizaLocalFrame.setVisible(true);
    }//GEN-LAST:event_ListarLugaresActionPerformed

    private void RemoverLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverLugaresActionPerformed
        RemoveLocal removeLugarFrame = new RemoveLocal();
        removeLugarFrame.setVisible(true);
    }//GEN-LAST:event_RemoverLugaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarLugares;
    private javax.swing.JMenuItem EditarLugares;
    private javax.swing.JMenuItem EditarUsuario;
    private javax.swing.JMenuItem ListarLugares;
    private javax.swing.JMenu Lugares;
    private javax.swing.JMenu MinhasInfos;
    private javax.swing.JMenuItem RemoverLugares;
    private javax.swing.JMenuItem VisualizarUsuarios;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
